#!/usr/bin/env node
// agent-stack installer — local web UI on http://127.0.0.1:7070
// Pure Node built-ins (http, fs, child_process, path, url, crypto). No npm deps.

import http from 'node:http';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import crypto from 'node:crypto';

const HOST = '127.0.0.1';
const PORT = 7070;
const DEMO = process.env.INSTALLER_DEMO === '1';
const STACK_DIR = process.env.STACK_DIR || '/opt/agent-stack';
const HERE = path.dirname(url.fileURLToPath(import.meta.url));

// --- helpers ----------------------------------------------------------------

function sendJSON(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body),
    'Cache-Control': 'no-store',
  });
  res.end(body);
}

function sendText(res, code, text, type = 'text/plain; charset=utf-8') {
  res.writeHead(code, { 'Content-Type': type, 'Cache-Control': 'no-store' });
  res.end(text);
}

function readBody(req, limitBytes = 1024 * 256) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on('data', (c) => {
      size += c.length;
      if (size > limitBytes) {
        reject(new Error('body too large'));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

// Run a command (no shell — array argv), capture stdout. Resolves even on non-zero.
function probe(cmd, args, timeoutMs = 4000) {
  return new Promise((resolve) => {
    let done = false;
    let out = '';
    let err = '';
    let child;
    try {
      child = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (e) {
      resolve({ ok: false, version: '', error: String(e.message || e) });
      return;
    }
    const timer = setTimeout(() => {
      if (done) return;
      done = true;
      try { child.kill('SIGKILL'); } catch {}
      resolve({ ok: false, version: '', error: 'timeout' });
    }, timeoutMs);
    child.stdout.on('data', (c) => (out += c.toString()));
    child.stderr.on('data', (c) => (err += c.toString()));
    child.on('error', (e) => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      resolve({ ok: false, version: '', error: String(e.message || e) });
    });
    child.on('close', (code) => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      const version = (out || err).trim().split('\n')[0] || '';
      resolve({ ok: code === 0, version, error: code === 0 ? '' : (err.trim() || `exit ${code}`) });
    });
  });
}

// --- /api/detect ------------------------------------------------------------

async function handleDetect(res) {
  const [nodeR, claudeR, codexR, geminiR, caddyR] = await Promise.all([
    probe('node', ['--version']),
    probe('/usr/bin/claude', ['--version']).then((r) => r.ok ? r : probe('claude', ['--version'])),
    probe('codex', ['--version']),
    probe('gemini', ['--version']),
    probe('caddy', ['version']),
  ]);
  const stackOk = fs.existsSync(STACK_DIR);
  sendJSON(res, 200, {
    node: nodeR,
    claude: claudeR,
    codex: codexR,
    gemini: geminiR,
    caddy: caddyR,
    stack: { ok: stackOk, version: stackOk ? STACK_DIR : '' },
    demo: DEMO,
  });
}

// --- /api/env ---------------------------------------------------------------

function safeStr(v, fallback = '') {
  if (v === undefined || v === null) return fallback;
  const s = String(v);
  // strip CR/LF to avoid sneaking new KEY=val lines
  return s.replace(/[\r\n]+/g, ' ').trim();
}

function pickEnum(v, allowed, fallback) {
  const s = safeStr(v);
  return allowed.includes(s) ? s : fallback;
}

function rand(n = 48) {
  return crypto.randomBytes(n).toString('base64url').slice(0, n);
}

function buildProxyEnv(cfg) {
  const backend = pickEnum(cfg.LLM_BACKEND, ['cli', 'api'], 'cli');
  const cliProvider = pickEnum(cfg.CLI_PROVIDER, ['claude', 'codex', 'gemini'], 'claude');
  const proxyKey = safeStr(cfg.PROXY_API_KEY) || rand(48);
  const jwtSecret = safeStr(cfg.JWT_SECRET) || rand(48);
  const lines = [
    '# generated by agent-stack installer',
    'HOST=127.0.0.1',
    'PORT=3001',
    `LLM_BACKEND=${backend}`,
    `CLI_PROVIDER=${cliProvider}`,
    `CLI_MODEL=${safeStr(cfg.CLI_MODEL)}`,
    'CLI_TIMEOUT_MS=120000',
    `KIMI_BASE_URL=${safeStr(cfg.KIMI_BASE_URL)}`,
    `KIMI_API_KEY=${safeStr(cfg.KIMI_API_KEY)}`,
    `KIMI_MODEL=${safeStr(cfg.KIMI_MODEL)}`,
    `PROXY_API_KEY=${proxyKey}`,
    `JWT_SECRET=${jwtSecret}`,
    `PUBLIC_BASE=${safeStr(cfg.PUBLIC_BASE)}`,
    '',
  ];
  return { content: lines.join('\n'), proxyKey, jwtSecret };
}

function buildUiEnv(cfg) {
  const lines = [
    '# generated by agent-stack installer',
    `AUTH_USER=${safeStr(cfg.AUTH_USER) || 'admin'}`,
    `AUTH_PASSWORD=${safeStr(cfg.AUTH_PASSWORD)}`,
    'KIMI_PROXY_URL=http://127.0.0.1:3001',
    '',
  ];
  return lines.join('\n');
}

async function handleEnv(req, res) {
  let body;
  try {
    body = JSON.parse(await readBody(req));
  } catch (e) {
    sendJSON(res, 400, { ok: false, error: 'bad json: ' + e.message });
    return;
  }
  const proxyDir = path.join(STACK_DIR, 'kimi-mcp-proxy');
  const uiDir = path.join(STACK_DIR, 'ai-chat-ui');
  const written = [];
  const proxyEnvPath = path.join(proxyDir, '.env');
  const uiEnvPath = path.join(uiDir, '.env.local');
  const { content: proxyContent, proxyKey } = buildProxyEnv(body);
  const uiContent = buildUiEnv(body);
  try {
    if (fs.existsSync(proxyDir)) {
      fs.writeFileSync(proxyEnvPath, proxyContent, { mode: 0o600 });
      written.push(proxyEnvPath);
    }
    if (fs.existsSync(uiDir)) {
      fs.writeFileSync(uiEnvPath, uiContent, { mode: 0o600 });
      written.push(uiEnvPath);
    }
  } catch (e) {
    sendJSON(res, 500, { ok: false, error: 'write failed: ' + e.message, written });
    return;
  }
  sendJSON(res, 200, { ok: true, written, proxyApiKey: proxyKey });
}

// --- /api/run (SSE) ---------------------------------------------------------

// Whitelist: step -> array of {cmd, args} OR demoLine[]
const STEPS = {
  deps: {
    label: 'Базовые пакеты (curl, ca-certificates, gnupg, git, ufw)',
    real: [
      ['apt-get', ['update']],
      ['apt-get', ['install', '-y', 'curl', 'ca-certificates', 'gnupg', 'git', 'ufw']],
    ],
  },
  node: {
    label: 'Node.js 20.x',
    real: [
      ['bash', ['-c', 'curl -fsSL https://deb.nodesource.com/setup_20.x | bash -']],
      ['apt-get', ['install', '-y', 'nodejs']],
      ['node', ['-v']],
    ],
  },
  'proxy-deps': {
    label: 'npm install в kimi-mcp-proxy',
    real: [
      ['npm', ['--prefix', path.join(STACK_DIR, 'kimi-mcp-proxy'), 'install', '--omit=dev']],
    ],
  },
  'ui-deps': {
    label: 'npm install + build в ai-chat-ui',
    real: [
      ['npm', ['--prefix', path.join(STACK_DIR, 'ai-chat-ui'), 'install']],
      ['npm', ['--prefix', path.join(STACK_DIR, 'ai-chat-ui'), 'run', 'build']],
    ],
  },
  services: {
    label: 'Установка systemd-юнитов',
    real: [
      ['cp', [path.join(STACK_DIR, 'deploy/systemd/kimi-mcp-proxy.service'), '/etc/systemd/system/']],
      ['cp', [path.join(STACK_DIR, 'deploy/systemd/ai-chat-ui.service'), '/etc/systemd/system/']],
      ['systemctl', ['daemon-reload']],
      ['systemctl', ['enable', '--now', 'kimi-mcp-proxy']],
      ['systemctl', ['enable', '--now', 'ai-chat-ui']],
    ],
  },
  verify: {
    label: 'Проверка /health',
    real: [
      ['curl', ['-fsS', 'http://127.0.0.1:3001/health']],
    ],
  },
};

function sseInit(res) {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache, no-transform',
    'Connection': 'keep-alive',
    'X-Accel-Buffering': 'no',
  });
}

function sseSend(res, event, data) {
  const lines = String(data).split('\n');
  if (event) res.write(`event: ${event}\n`);
  for (const ln of lines) res.write(`data: ${ln}\n`);
  res.write('\n');
}

function runSeq(res, jobs, onDone) {
  let idx = 0;
  const step = () => {
    if (idx >= jobs.length) { onDone(0); return; }
    const [cmd, args] = jobs[idx++];
    sseSend(res, null, `$ ${cmd} ${args.join(' ')}`);
    let child;
    try {
      child = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (e) {
      sseSend(res, null, 'ERROR: ' + e.message);
      onDone(1);
      return;
    }
    child.stdout.on('data', (c) => sseSend(res, null, c.toString().replace(/\n$/, '')));
    child.stderr.on('data', (c) => sseSend(res, null, c.toString().replace(/\n$/, '')));
    child.on('close', (code) => {
      if (code !== 0) {
        sseSend(res, null, `[exit ${code}]`);
        onDone(code || 1);
        return;
      }
      step();
    });
    child.on('error', (e) => { sseSend(res, null, 'spawn error: ' + e.message); onDone(1); });
  };
  step();
}

function runDemo(res, step, onDone) {
  const jobs = STEPS[step].real;
  let i = 0;
  const tick = () => {
    if (i >= jobs.length) { sseSend(res, null, 'DEMO: завершено успешно'); onDone(0); return; }
    const [cmd, args] = jobs[i++];
    sseSend(res, null, `[demo] would run: ${cmd} ${args.join(' ')}`);
    setTimeout(tick, 350);
  };
  sseSend(res, null, `[demo] шаг: ${STEPS[step].label}`);
  tick();
}

async function handleRun(req, res) {
  const parsed = url.parse(req.url, true);
  const step = String(parsed.query.step || '');
  if (!Object.prototype.hasOwnProperty.call(STEPS, step)) {
    sendJSON(res, 400, { ok: false, error: 'unknown step', allowed: Object.keys(STEPS) });
    return;
  }
  sseInit(res);
  sseSend(res, 'start', JSON.stringify({ step, demo: DEMO }));
  const onDone = (code) => {
    sseSend(res, 'done', JSON.stringify({ code }));
    res.end();
  };
  if (DEMO) runDemo(res, step, onDone);
  else runSeq(res, STEPS[step].real, onDone);
}

// --- /api/cli-login ---------------------------------------------------------

async function handleCliLogin(req, res) {
  let body = {};
  try { body = JSON.parse(await readBody(req)); } catch {}
  const provider = pickEnum(body.provider, ['claude', 'codex', 'gemini'], 'claude');
  if (DEMO) {
    sendJSON(res, 200, {
      ok: true,
      demo: true,
      message: `[demo] запустите вручную: ${provider} login (в интерактивном терминале)`,
      hint: 'CLI требует TTY — авторизуйтесь в обычной SSH-сессии, затем продолжайте мастер.',
    });
    return;
  }
  // Real CLI login needs a TTY — we can't drive it from a web request.
  // Return instructions instead of pretending to launch it.
  const cmd = provider === 'claude' ? '/usr/bin/claude login'
    : provider === 'codex' ? 'codex login'
    : 'gemini auth';
  sendJSON(res, 200, {
    ok: true,
    requiresTty: true,
    message: `Авторизация CLI требует терминал. Выполните в SSH-сессии: ${cmd}`,
    command: cmd,
  });
}

// --- static index.html ------------------------------------------------------

function handleIndex(res) {
  const p = path.join(HERE, 'index.html');
  try {
    const html = fs.readFileSync(p);
    res.writeHead(200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
      'Content-Length': html.length,
    });
    res.end(html);
  } catch (e) {
    sendText(res, 500, 'index.html missing: ' + e.message);
  }
}

// --- router -----------------------------------------------------------------

const server = http.createServer(async (req, res) => {
  // hard guard: only local
  const ra = req.socket.remoteAddress || '';
  if (!(ra === '127.0.0.1' || ra === '::1' || ra === '::ffff:127.0.0.1')) {
    sendText(res, 403, 'forbidden: localhost only');
    return;
  }
  const u = url.parse(req.url || '/', true);
  const pathname = u.pathname || '/';
  try {
    if (req.method === 'GET' && pathname === '/') return handleIndex(res);
    if (req.method === 'GET' && pathname === '/api/detect') return handleDetect(res);
    if (req.method === 'POST' && pathname === '/api/env') return handleEnv(req, res);
    if (req.method === 'GET' && pathname === '/api/run') return handleRun(req, res);
    if (req.method === 'POST' && pathname === '/api/cli-login') return handleCliLogin(req, res);
    if (req.method === 'GET' && pathname === '/api/health') return sendJSON(res, 200, { ok: true, demo: DEMO });
    sendText(res, 404, 'not found');
  } catch (e) {
    sendJSON(res, 500, { ok: false, error: String(e.message || e) });
  }
});

server.listen(PORT, HOST, () => {
  process.stdout.write(
    `agent-stack installer on http://${HOST}:${PORT}  ` +
    `(demo=${DEMO ? 'on' : 'off'}, stack=${STACK_DIR})\n`
  );
});
